### ISSUE TITLE
mode-line-keycast let user propertize output for mode-line.

### ISSUE THREAD

**Issue by mohkale** [tarsius/keycast#10]
eg.

```elisp
(setq keycast-mode-line-format #'my-keycast-mode-line-format)

(defun my-keycast-mode-line-format (key cmd)
  (concat key " | " command))
```

**Comment by tarsius** [comment]
So basically things should look as they are now but there should be a pipe between the key and the command?

**Comment by mohkale** [comment]
Actually I was hoping to remove the face and default properties to make it better integrate with spaceline, so the default format would be:

```elisp
(defun keycast-mode-line-format (key cmd)
  (concat
   (propertize (let ((pad (max 2 (- 5 (length key)))))
                 (concat (make-string (ceiling pad 2) ?\s) key
                         (make-string (floor   pad 2) ?\s)))
               'face 'keycast-key)
   (propertize (format " %s" cmd) 'face 'keycast-command)
   (and (> keycast--command-repetitions 0)
        (format " x%s" (1+ keycast--command-repetitions)))))
```

which would be called after concatenating the `keycast-separator-width`.

**Comment by tarsius** [comment]
> Actually I was hoping to remove the face and default properties to make it better integrate with spaceline,

It wasn't my intention for this information to "integrate well" with the overall look of the mode-line. Quite the opposite, this is supposed to look different and like a button (like a physical key actually) so that people who watch a screencast notice this information. That isn't limited to spaceline; when using a fairly standard mode-line or my `moody` package, then the information displayed by this package also does not blend in.

Are you using this package as a "what did I just type" kinda mode?

> Actually I was hoping to remove the face and default properties

You could just change the faces instead, making them identical to the `mode-line` face (or the spaceline equivalent).

What "default property" are you talking about?

**Comment by mohkale** [comment]
> Are you using this package as a "what did I just type" kinda mode?

Pretty much, yeah. I like my mode line to be homogonised, so having something unexpected clearly stand out isn't very appealing to me 😅. If it needs to stand out I generally just make it bold, which has enough of the desired affect.

> You could just change the faces instead, making them identical to the mode-line face (or the spaceline equivalent).

Normally I would, except spaceline consists of segments and each segment changes faces as new segments get introduced; in my experience specifying a fixed foreground or background causes that attribute to not get updated when segments change. I could try setting keycasts face to inherit everything; for now I'll try that.

However in this case I felt letting users have the option to propertize the output would be the least invasive way to go about it.

> What "default property" are you talking about?

Hypothetically if you introduce a `keycast-mode-line-format` option, then the method given above would result in the same output as we have now. Sorry if that wasn't clear enough 😞.

**Comment by tarsius** [comment]
> [on #9 you said] If you feel this is too needy then feel free to ignore that. It's not a huge issue, though could come in useful if any other packages want to build on keycast somewhere down the line.

Not *needy*, but...

> Normally I would, except spaceline consists of segments and each segment changes faces as new segments get introduced;

I wrote my own "pretty mode-line" package called `moody` because of the following characteristics of popular existing solutions that derive, extend or were inspired by `powerline`.

1. Segments change appearance depending on whether the respective window is selected. Unlike for standard mode-line this goes beyond toggling between active and inactive color. Instead of these boolean switch there are (more than two) numbered colors, which do not correspond to the two states but segments use different colors depending on the boolean state anyway, but in completely unpredictable ways that have no semantic reason behind them. The directions of images around/between segments may also change in essentially random ways.
2. The official api is not respected. Most importantly the format is not a list of elements but a single function (which may or may not internally use lists or trees of elements).

IMO these are pretty grave defects. (1) is a personal preference I suppose, but the spapeshifting of sements made these package unusable for me. I looked into changing just that, which lead me to discover (2).

I then decided that it would be easier to start over and write a few composable packages instead. Instead of banging existing solutions into shape, more or less, I wrote my own simple solutions.

They work well and compose, as long as the mode-line prettifier conforms to the api. Explicitly supporting these third-party prettifiers goes against what motivated me to write these packages in the first place, namely *not* having to deal with them. 

So I have decided to not make the requested changes. If I went down the road of supporting these third-party packages I tried getting away from, then I would eventually strongly dislike working on this and similar packages as [has happened](https://github.com/tarsius/hl-todo/issues/50) for `hl-todo`

**Comment by mohkale** [comment]
Fair enough. Thnx for hearing me out 😄.

**Comment by tarsius** [comment]
While cleaning up I came across an old draft and decided to implement this after all.  See the new `mode-line-keycast-format` option.
