### ISSUE TITLE
Universal argument & digit argument

### ISSUE THREAD

**Issue by psionic-k** [tarsius/keycast#32]
https://github.com/tarsius/keycast/pull/31  Follow-up

I checked out master and was satisfied with the M-x behavior.  Thanks for changes.

With all three choices for `keycast-show-minibuffer-exit-command`, I was unable to properly show `digit-argument` and `universal-argument`.  `universal-argument-more` will likely be similar.  Those are just the commands I was aware of requiring special cases depending on the user's intent.

The blunt approach of recording and comparing values during pre-command-hook and post-command-hook is at the very least haphazardly obtaining correct values for these cases.

I'm a little bit uncomfortable with using explicit key sequences such as `M-x`, but possibly I should read more to understand how it is consistent if bindings are customized?

Do you know if `universal-argument` and `execute-extended-command` interact with the command loop states similarly?

Thanks in advance for further advising changes.

**Comment by tarsius** [comment]
Thanks for pointing out such issues! Since I don't actually do screencasts, I have little opportunity to notice such unhandled special-cases.

> The blunt approach of recording and comparing values during pre-command-hook and post-command-hook is at the very least haphazardly obtaining correct values for these cases.

Well, *these* commands fiddle with `this-command`. But they leave `this-original-command` alone, so this is trivial to detect and deal with. c4a995a468cef6a5468add44fc5702b073a6c3ca

> Do you know if `universal-argument` and `execute-extended-command` interact with the command loop states similarly?

No, not at all. All `universal-argument` et al. do, is to set a global variable (and mess with a few additional global variables (resulting in this issue). `execute-extended-command` uses the minibuffer and then calls `command-exectute`.

I recommend you read the implementations of these two features. They are both rather short.

The implementation of prefix arguments is surprisingly simple. At the core of Transient there is the same trivial idea, but obviously it then packs a lot of functionality (and complexity) on top of that. That's why I've described Transient as "prefix arguments on steroids" before (I think).
