### ISSUE TITLE
custom-initialize-reset: Cannot turn on keycast-mode-line-mode.  mode-line-end-spaces not found in mode-line-format.

### ISSUE THREAD

**Issue by getong** [tarsius/keycast#34]
emacs 29.3 on macos
```
custom-initialize-reset: Cannot turn on keycast-mode-line-mode.  mode-line-end-spaces not found in mode-line-format.  Try customizing keycast-mode-line-insert-after.
```
config sample:
```
(use-package keycast
  :straight t
  :hook (after-init . keycast-mode-line-mode)
  :config
  (setq keycast-mode-line-format "%5s%K%C%r")
  (setq keycast-mode-line-remove-tail-elements nil)
  (setq keycast-mode-line-insert-after 'mode-line-end-spaces))
```
or
```
(use-package keycast
  :straight t
  :config
  (keycast-mode-line-mode)
  (define-minor-mode keycast-mode
    "Keycast mode"
    :global t
    (if keycast-mode
	      (progn
	        (add-to-list 'global-mode-string '("" keycast-mode-line " "))
	        (add-hook 'pre-command-hook 'keycast--update t) )
      (remove-hook 'pre-command-hook 'keycast--update)
      (setq global-mode-string (delete '("" keycast-mode-line " ") global-mode-string)))))
```

**Comment by tarsius** [comment]
`mode-line-end-spaces` has been a member of `mode-line-format`'s default value for twelve years (since https://github.com/emacsmirror/emacs/commit/5f2c76c6cee2b5d2d84ffd409839fd58d2ad16fa).

If that is not the case for you then something probably removes it (try with `emacs -Q`).

Look at the value of `mode-line-format` and decide after which actual element of that list you want to add the keycast element. Then customize `keycast-mode-line-insert-after` accordingly.

**Comment by tarsius** [comment]
> More generally, enabling `keycast-mode-line-mode` **while it is already enabled**

I consider that a user error and have added a kludge to recover from it.
